# Generated by Django 4.0.5 on 2022-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devlittlegirls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='home_page',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='nome_site',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
