# Generated by Django 4.0.5 on 2022-06-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devlittlegirls_app', '0004_alter_site_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='tb_site',
        ),
    ]
