# Generated by Django 4.0.5 on 2022-06-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Devlittlegirls_app', '0006_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
    ]
